COUNTRIES = (
    ('AFGHANISTAN','Afghanistan'),
    ('ALBANIA','Albania'),
    ('ALGERIA','Algeria'),
    ('AMERICAN_SAMOA','American Samoa'),
    ('ANDORRA','Andorra'),
    ('ANGOLA','Angola'),
    ('ANGUILLA','Anguilla'),
    ('ANTIGUA','Antigua & Barbuda'),
    ('ARGENTINA','Argentina'),
    ('ARMENIA','Armenia'),
    ('ARUBA','Aruba'),
    ('AUSTRALIA','Australia'),
    ('AUSTRIA','Austria'),
    ('AZERBAIJAN','Azerbaijan'),
    ('BAHAMAS','Bahamas, The'),
    ('BAHRAIN','Bahrain'),
    ('BANGLADESH','Bangladesh'),
    ('BARBADOS','Barbados'),
    ('BELARUS','Belarus'),
    ('BELGIUM','Belgium'),
    ('BELIZE','Belize'),
    ('BENIN','Benin'),
    ('BERMUDA','Bermuda'),
    ('BHUTAN','Bhutan'),
    ('BOLIVIA','Bolivia'),
    ('BOSNIA','Bosnia & Herzegovina'),
    ('BOTSWANA','Botswana'),
    ('BRAZIL','Brazil'),
    ('BRITISH_VIRGIN_IS.','British Virgin Is.'),
    ('BRUNEI','Brunei'),
    ('BULGARIA','Bulgaria'),
    ('BURKINA_FASO','Burkina Faso'),
    ('BURMA','Burma'),
    ('BURUNDI','Burundi'),
    ('CAMBODIA','Cambodia'),
    ('CAMEROON','Cameroon'),
    ('CANADA','Canada'),
    ('CAPE_VERDE','Cape Verde'),
    ('CAYMAN_ISLANDS','Cayman Islands'),
    ('CENTRAL_AFRICAN_REP.','Central African Rep.'),
    ('CHAD','Chad'),
    ('CHILE','Chile'),
    ('CHINA','China'),
    ('COLOMBIA','Colombia'),
    ('COMOROS','Comoros'),
    ('CONGO,_DEM._REP.','Congo, Dem. Rep.'),
    ('CONGO,_REPUB._OF THE','Congo, Repub. of the'),
    ('COOK_ISLANDS','Cook Islands'),
    ('COSTA_RICA','Costa Rica'),
    ('COTE_DIVOIRE','Cote d'Ivoire'),
    ('CROATIA','Croatia'),
    ('CUBA','Cuba'),
    ('CYPRUS','Cyprus'),
    ('CZECH_REPUBLIC','Czech Republic'),
    ('DENMARK','Denmark'),
    ('DJIBOUTI','Djibouti'),
    ('DOMINICA','Dominica'),
    ('DOMINICAN_REPUBLIC','Dominican Republic'),
    ('EAST_TIMOR','East Timor'),
    ('ECUADOR','Ecuador'),
    ('EGYPT','Egypt'),
    ('EL_SALVADOR','El Salvador'),
    ('EQUATORIAL_GUINEA','Equatorial Guinea'),
    ('ERITREA','Eritrea'),
    ('ESTONIA','Estonia'),
    ('ETHIOPIA','Ethiopia'),
    ('FAROE_ISLANDS','Faroe Islands'),
    ('FIJI','Fiji'),
    ('FINLAND','Finland'),
    ('FRANCE','France'),
    ('FRENCH_GUIANA','French Guiana'),
    ('FRENCH_POLYNESIA','French Polynesia'),
    ('GABON','Gabon'),
    ('GAMBIA,_THE','Gambia, The'),
    ('GAZA_STRIP','Gaza Strip'),
    ('GEORGIA','Georgia'),
    ('GERMANY','Germany'),
    ('GHANA','Ghana'),
    ('GIBRALTAR','Gibraltar'),
    ('GREECE','Greece'),
    ('GREENLAND','Greenland'),
    ('GRENADA','Grenada'),
    ('GUADELOUPE','Guadeloupe'),
    ('GUAM','Guam'),
    ('GUATEMALA','Guatemala'),
    ('GUERNSEY','Guernsey'),
    ('GUINEA','Guinea'),
    ('GUINEA-BISSAU','Guinea-Bissau'),
    ('GUYANA','Guyana'),
    ('HAITI','Haiti'),
    ('HONDURAS','Honduras'),
    ('HONG_KONG','Hong Kong'),
    ('HUNGARY','Hungary'),
    ('ICELAND','Iceland'),
    ('INDIA','India'),
    ('INDONESIA','Indonesia'),
    ('IRAN','Iran'),
    ('IRAQ','Iraq'),
    ('IRELAND','Ireland'),
    ('ISLE_OF_MAN','Isle of Man'),
    ('ISRAEL','Israel'),
    ('ITALY','Italy'),
    ('JAMAICA','Jamaica'),
    ('JAPAN','Japan'),
    ('JERSEY','Jersey'),
    ('JORDAN','Jordan'),
    ('KAZAKHSTAN','Kazakhstan'),
    ('KENYA','Kenya'),
    ('KIRIBATI','Kiribati'),
    ('KOREA_NORTH','Korea, North'),
    ('KOREA_SOUTH','Korea, South'),
    ('KUWAIT','Kuwait'),
    ('KYRGYZSTAN','Kyrgyzstan'),
    ('LAOS','Laos'),
    ('LATVIA','Latvia'),
    ('LEBANON','Lebanon'),
    ('LESOTHO','Lesotho'),
    ('LIBERIA','Liberia'),
    ('LIBYA','Libya'),
    ('LIECHTENSTEIN','Liechtenstein'),
    ('LITHUANIA','Lithuania'),
    ('LUXEMBOURG','Luxembourg'),
    ('MACAU','Macau'),
    ('MACEDONIA','Macedonia'),
    ('MADAGASCAR','Madagascar'),
    ('MALAWI','Malawi'),
    ('MALAYSIA','Malaysia'),
    ('MALDIVES','Maldives'),
    ('MALI','Mali'),
    ('MALTA','Malta'),
    ('MARSHALL_ISLANDS','Marshall Islands'),
    ('MARTINIQUE','Martinique'),
    ('MAURITANIA','Mauritania'),
    ('MAURITIUS','Mauritius'),
    ('MAYOTTE','Mayotte'),
    ('MEXICO','Mexico'),
    ('MICRONESIA,_FED._ST.','Micronesia, Fed. St.'),
    ('MOLDOVA','Moldova'),
    ('MONACO','Monaco'),
    ('MONGOLIA','Mongolia'),
    ('MONTSERRAT','Montserrat'),
    ('MOROCCO','Morocco'),
    ('MOZAMBIQUE','Mozambique'),
    ('NAMIBIA','Namibia'),
    ('NAURU','Nauru'),
    ('NEPAL','Nepal'),
    ('NETHERLANDS','Netherlands'),
    ('NETHERLANDS_ANTILLES','Netherlands Antilles'),
    ('NEW_CALEDONIA','New Caledonia'),
    ('NEW_ZEALAND','New Zealand'),
    ('NICARAGUA','Nicaragua'),
    ('NIGER','Niger'),
    ('NIGERIA','Nigeria'),
    ('N_MARIANA_ISLANDS','N. Mariana Islands'),
    ('NORWAY','Norway'),
    ('OMAN','Oman'),
    ('PAKISTAN','Pakistan'),
    ('PALAU','Palau'),
    ('PANAMA','Panama'),
    ('PAPUA_NEW_GUINEA','Papua New Guinea'),
    ('PARAGUAY','Paraguay'),
    ('PERU','Peru'),
    ('PHILIPPINES','Philippines'),
    ('POLAND','Poland'),
    ('PORTUGAL','Portugal'),
    ('PUERTO_RICO','Puerto Rico'),
    ('QATAR','Qatar'),
    ('REUNION','Reunion'),
    ('ROMANIA','Romania'),
    ('RUSSIA','Russia'),
    ('RWANDA','Rwanda'),
    ('SAINT_HELENA','Saint Helena'),
    ('SAINT_KITTS','Saint Kitts & Nevis'),
    ('ST_LUCA','Saint Lucia'),
    ('STPIERRE','St Pierre & Miquelon'),
    ('SAINT_VINCENT_ GRENADINES','Saint Vincent and the Grenadines'),
    ('SAMOA','Samoa'),
    ('SAN_MARINO','San Marino'),
    ('SAO_TOME','Sao Tome & Principe'),
    ('SAUDI_ARABIA','Saudi Arabia'),
    ('SENEGAL','Senegal'),
    ('SERBIA','Serbia'),
    ('SEYCHELLES','Seychelles'),
    ('SIERRA_LEONE','Sierra Leone'),
    ('SINGAPORE','Singapore'),
    ('SLOVAKIA','Slovakia'),
    ('SLOVENIA','Slovenia'),
    ('SOLOMON_ISLANDS','Solomon Islands'),
    ('SOMALIA','Somalia'),
    ('SOUTH_AFRICA','South Africa'),
    ('SPAIN','Spain'),
    ('SRI_LANKA','Sri Lanka'),
    ('SUDAN','Sudan'),
    ('SURINAME','Suriname'),
    ('SWAZILAND','Swaziland'),
    ('SWEDEN','Sweden'),
    ('SWITZERLAND','Switzerland'),
    ('SYRIA','Syria'),
    ('TAIWAN','Taiwan'),
    ('TAJIKISTAN','Tajikistan'),
    ('TANZANIA','Tanzania'),
    ('THAILAND','Thailand'),
    ('TOGO','Togo'),
    ('TONGA','Tonga'),
    ('TRINIDAD','Trinidad & Tobago'),
    ('TUNISIA','Tunisia'),
    ('TURKEY','Turkey'),
    ('TURKMENISTAN','Turkmenistan'),
    ('TURKS','Turks & Caicos Is'),
    ('TUVALU','Tuvalu'),
    ('UGANDA','Uganda'),
    ('UKRAINE','Ukraine'),
    ('UNITED_ARAB_EMIRATES','United Arab Emirates'),
    ('UNITED_KINGDOM','United Kingdom'),
    ('UNITED_STATES','United States'),
    ('URUGUAY','Uruguay'),
    ('UZBEKISTAN','Uzbekistan'),
    ('VANUATU','Vanuatu'),
    ('VENEZUELA','Venezuela'),
    ('VIETNAM','Vietnam'),
    ('VIRGIN_ISLANDS','Virgin Islands'),
    ('WALLIS_AND_FUTUNA','Wallis and Futuna'),
    ('WEST_BANK','West Bank'),
    ('WESTERN_SAHARA','Western Sahara'),
    ('YEMEN','Yemen'),
    ('ZAMBIA','Zambia'),
    ('ZIMBABWE','Zimbabwe'),
)
